apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-01
  name: deployment-01
  namespace: dev-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-01
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-01
        color: blue
    spec:
      containers:
      - image: nginx:1.20.1
        name: pod-in-deployment-01-container
        resources: {}
status: {}
